### ISSUE TITLE
Update CTRL panel "+Add CTRL" widget button to match Flow Chart "+Add Node" button

### ISSUE THREAD

**Issue by jackparmer** [flojoy-io/studio#266]
This new UI for adding nodes is really nice:
<img width="448" alt="image" src="https://user-images.githubusercontent.com/1865834/226746719-6b606e3e-ae67-4fc4-9832-c1acdcf97640.png">

We should match it in the CTRLs tab for this UI:
<img width="894" alt="image" src="https://user-images.githubusercontent.com/1865834/226748006-08db2c33-fda6-4285-9202-3050c61e381f.png">

"+Add CTRL" should also be present and automatically switch the CTRL panel into edit mode. It's annoying and not intuitive to toggle the edit switch every time.

To make room for the "+Add CTRL" button, we'll need to create some margin on the left of the CTRLS canvas here:
<img width="376" alt="image" src="https://user-images.githubusercontent.com/1865834/226748351-dea06273-ab10-4ca7-bb6a-ef715c54dee6.png">

**Comment by jackparmer** [comment]
should also write a docs page as part of this PR
https://github.com/flojoy-io/docs/issues/23

**Comment by jackparmer** [comment]
Here's a lo-fi mock to clarify where each widget goes in the sidebar:

<img width="293" alt="image" src="https://user-images.githubusercontent.com/1865834/235790058-756ca83d-f815-4d2b-bda7-df23244a9265.png">

**Comment by jackparmer** [comment]
came across this Figma that suggests input/output tabs on top - seems p. nice

<img width="366" alt="image" src="https://user-images.githubusercontent.com/1865834/235794826-e3129db1-d392-458f-abff-2de4e0de57fb.png">

https://www.figma.com/file/aKeN0DN5b1wy8My5Zap0Wt/Flojoy

**Comment by izi-on** [comment]
> came across this Figma that suggests input/output tabs on top - seems p. nice
> 
> <img alt="image" width="366" src="https://user-images.githubusercontent.com/1865834/235794826-e3129db1-d392-458f-abff-2de4e0de57fb.png">
> 
> https://www.figma.com/file/aKeN0DN5b1wy8My5Zap0Wt/Flojoy

Instead of adding a margin on the left, I will simply add the button on top like in the Figma :)

**Comment by izi-on** [comment]
merged into the style-refactor :)
