### ISSUE TITLE
Adding controls for default Queue timeout and default deadtime between node execution

### ISSUE THREAD

**Issue by trbritt** [flojoy-io/studio#305]
While I've been developing the PID app, there were two things that I came across that could be added to the UI for users that would potentially benefit application development and real-time usage

- An ability to directly control the default timeout for the queue in rq
       - For jobs that are expected to run for long long times, for example overnight, the value now in develop here may not be enough, or at least the user should be able to specify it IMO
- An ability to control the wait time between node execution
       - Having an option to specify if the nodes should be executed after a 1 second wait or be limited only by the execution time of a node would be very useful. 
       - My PID app, for example, involves systems that have time constants on the order of a few 100 milliseconds, which is an execution time python is definitely able to get below, so having the nodes be executed as quickly as possible would be of great benefit to the real-world implementation of this application

**Comment by jackparmer** [comment]
An easy starting-point UI for this could be simply a "Global App Settings" modal accessed from the File ⬇️  menu:

<img width="178" alt="image" src="https://user-images.githubusercontent.com/1865834/235792105-eb44e073-25c6-4a57-af61-f53e2cc1fe1e.png">

**Comment by jackparmer** [comment]
i believe this is implemented now
