### ISSUE TITLE
[E2E test] Adding and deleting a single node

### ISSUE THREAD

**Issue by jalium** [flojoy-io/studio#318]
E2E test for a single node

**Comment by jackparmer** [comment]
@youngsun4786 @Jin1L 
let's gooooo!

can be done via reflect.run

**Comment by youngsun4786** [comment]
Let's goooooo


> @youngsun4786 @Jin1L let's gooooo!
> 
> can be done via reflect.run

**Comment by Jin1L** [comment]
Made it in Reflect.run
