### ISSUE TITLE
parameter editor tray in SCRIPT tab

### ISSUE THREAD

**Issue by jackparmer** [flojoy-io/studio#324]
when making an app, it's hugely annoying to go into the CTRL panel and make a small dashboard just to test changing node parameter values

it would be nice to have a RHS tray like this accessible in the SCRIPTS tab (the tray opens when u click on the edit/pencil icon in the node)

<img width="741" alt="image" src="https://user-images.githubusercontent.com/1865834/235799384-017cc8b3-4a17-4eda-800b-eff15179ff2e.png">

(from https://www.figma.com/file/aKeN0DN5b1wy8My5Zap0Wt/Flojoy?node-id=11%3A2&t=NagAn7Zq3B9ha4XD-1)

parameters per node are cannonized here:
https://github.com/flojoy-io/nodes/tree/main/MANIFEST

I'd suggest this mapping as a starting point between parameter type and default widget:
- `float` - numeric input
- `string` - string input
- `boolean` - toggle switch
- TODO: other types? 

these new default parameters should be serialized as part of the react flow object, so that they can be recalled from a flojoy app saved to disk

**Comment by jackparmer** [comment]
@Angchau @trbritt @dstrande 
would love to hear thoughts, feedback, and suggestions on this UI, since you've spent the most amount of time trying to build example apps in `studio`

**Comment by Angchau** [comment]
Yes it would be great to change parameters directly from the script tab, for example for my node which controls the stepper motor from the knob position this would be so much better !!
