### ISSUE TITLE
UI Overhaul

### ISSUE THREAD

**Issue by itsjoeoui** [flojoy-io/studio#325]
- [ ] Starting Page
- [ ] AddNode View
- [ ] NodeDetail View
- [ ] Better ReactFlow Theme
- [ ] History View
- [ ] Disconnected View
- [ ] Right Sidebar
- [ ] CTRLS Page
- [ ] Dark Mode

**Comment by jackparmer** [comment]
datablocks has some nice UI inspo:
https://editor.datablocks.pro/demo
(a lot like flojoy but JS execution instead of Python)
