### ISSUE TITLE
[telemetry] cloud logs for Redis errors

### ISSUE THREAD

**Issue by jackparmer** [flojoy-io/studio#335]
beyond Sentry.io, might be nice to have a dedicated logging portal to observe Redis errors. would save us time in debugging user Redis issues if we didn't have to ask them to find or setup redis logs

@yassine-moumen might have suggestions for logging services to use for this (eg dynatrace?)

**Comment by yassine-moumen** [comment]
I completely understand the concern regarding the need for a dedicated logging portal to observe Redis errors. While Dynatrace is a great option for monitoring and observability, I think we can also consider using ELK Stack (Elasticsearch, Logstash, Kibana) or NewRelic for centralized logging and monitoring. 
Ultimately, the decision will come down to price and specific needs, so I suggest we evaluate both options and determine which one best fits our requirements.
I will evaluate each option and determine which one would be the most suitable for our needs.
