### ISSUE TITLE
REDIS-related 500 at `/wfc` ("write flow chart")

### ISSUE THREAD

**Issue by jackparmer** [flojoy-io/studio#336]
<img width="1121" alt="image" src="https://user-images.githubusercontent.com/1865834/236311731-647737fc-205e-4e8d-a04b-cf24c54d50f9.png">

related: https://github.com/flojoy-io/studio/issues/335

**Comment by itsjoeoui** [comment]
@jackparmer What are the steps to reproduce this exactly?

**Comment by jackparmer** [comment]
On my Mac in the office, I get this error simply from running `sh flojoy` 

<img width="580" alt="image" src="https://user-images.githubusercontent.com/1865834/236590317-326c4981-42f5-43cc-8fe3-c578f2b956a9.png">

**Comment by itsjoeoui** [comment]
@jackparmer Can I debug it on yours when I come on Monday? We should be able to get it resolved quickly that way.

**Comment by jackparmer** [comment]
Fixed this with 

```
brew update
brew install redis
brew services start redis
```
🤷 
Ref: https://stackoverflow.com/questions/19581059/misconf-redis-is-configured-to-save-rdb-snapshots

Closing for now, but good to keep in mind for the future when community.flojoy.io users run into this
