### ISSUE TITLE
add dropdown to discrete variable control options (and make sure appears on SCRIPT sidebar)

### ISSUE THREAD

**Issue by jackparmer** [flojoy-io/studio#403]
we're currently missing a dropdown control here:

<img width="365" alt="image" src="https://github.com/flojoy-io/studio/assets/1865834/e4abe99f-694f-4476-ada6-58ab8310bfae">

looks like "dropdown" was added to the control's manifest, but i guess did not make its way all the way to the UI:
https://github.com/flojoy-io/studio/blob/main/src/feature/controls_panel/manifest/CONTROLS_MANIFEST.ts#L129

a dropdown option would be useful here, for example, where there are only so many discrete options available (image names):

<img width="360" alt="image" src="https://github.com/flojoy-io/studio/assets/1865834/885ab217-ff14-4043-b999-c25df6ea4890">

**Comment by smahmed776** [comment]
For dropdown to appear here in the sidebar parameter type for node needs to be changed to `select` type with given available discrete options.

**Comment by jackparmer** [comment]
oh ok looks like this already works (at least for the sidebar, but perhaps not for the CTRL panel)

<img width="299" alt="image" src="https://github.com/flojoy-io/studio/assets/1865834/f15ef5de-2cb3-4805-a6b0-7ba6341e62ce">

https://github.com/flojoy-io/nodes/blob/main/MANIFEST/plotly_dataset.manifest.yaml#L7

**Comment by smahmed776** [comment]
Right, I just noticed that the dropdown is missing in CTRL_TREE here:https://github.com/flojoy-io/studio/blob/develop/src/feature/controls_panel/manifest/CONTROLS_MANIFEST.ts#L62

**Comment by jackparmer** [comment]
ASFAICT, i think that just R_DATASETS and SKLEARN_IMAGE are missing the dropdown configuration that PLOTLY_DATASETS has
