### ISSUE TITLE
prompt user to rerun app after making a parameter change

### ISSUE THREAD

**Issue by jackparmer** [flojoy-io/studio#404]
it's easy to think that the app will just automatically rerun itself after changing a parameter in the sidebar
i think that we should add a simple subtle prompt here on parameter changed:

<img width="407" alt="image" src="https://github.com/flojoy-io/studio/assets/1865834/34c82ea7-4c29-4b5b-acaa-3dc5f74b8710">

i think it can be as simple and subtle as this:

<img width="615" alt="image" src="https://github.com/flojoy-io/studio/assets/1865834/58a6f73a-134e-4cee-bdf4-1bbd13a0eed6">

**Comment by Gauravvpnd** [comment]
Hey i would love to work on this issue can you assign me this
