### ISSUE TITLE
[VIZ] table styling

### ISSUE THREAD

**Issue by jackparmer** [flojoy-io/studio#405]
the viz table is pretty sweet!

<img width="788" alt="image" src="https://github.com/flojoy-io/studio/assets/1865834/3bce84a8-370d-4c27-87d5-d7224825d777">

i noticed a few potential UI improvements:

- [x] i would limit the number of columns on display in the thumbnail to 4 and the number of rows to 20 (only in the thumbnail - not in the expanded view when you click on the modal - the full table looks great there)
- [x] in dark mode, the cell background should be transparent to match the background of the canvas. the text and line colors should be light-flojoy-grey. the table styling looks much better in light mode

<img width="757" alt="image" src="https://github.com/flojoy-io/studio/assets/1865834/0f9af7df-8a80-4789-b501-fe044edbb973">

**Comment by Gauravvpnd** [comment]
Hey, i would like to work on this issue can you explain to me a little about what are changes need to made and assign me this?

**Comment by smahmed776** [comment]
Hi, @Gauravvpnd can you find other potential issues from the list as there is an existing PR that can cover this issue as well. https://github.com/flojoy-io/studio/pull/392
