### ISSUE TITLE
[VIZ] Data structures

### ISSUE THREAD

**Issue by jackparmer** [flojoy-io/studio#429]
New VIZ category called "Data structures" (at the same level as the "Plotly" category) to inspect `DataContainers` carrying numpy arrays or numpy 2d matrices

After some playing around, I think that this can be done using Plotly tables. For example, here's how I would like matrix previews to look, for example:

<img width="162" alt="image" src="https://github.com/flojoy-io/studio/assets/1865834/9eef5407-c2ff-43a7-9ee1-d0fc7b7e9431">

(Link to plotly: https://plotly.com/~jackp/18889/) 

Noticed that I used Katex for the diagonal and vertical ellipses: 
<img width="351" alt="image" src="https://github.com/flojoy-io/studio/assets/1865834/883d63fe-4fb7-43c2-8e2a-bc23a6c557c5">

Arrays can be simple tables that are a single row or a single column, like this:
<img width="153" alt="image" src="https://github.com/flojoy-io/studio/assets/1865834/a668dd38-e7f4-4534-ac90-5ba4e8832829">
<img width="40" alt="image" src="https://github.com/flojoy-io/studio/assets/1865834/e3221e66-94e1-4e60-90e6-f45585ee4457">

(their orientation should respect their numpy axis - https://www.sharpsightlabs.com/blog/numpy-axes-explained/)

A few considerations
- [x] Maximum matrix preview size of 4 x 4 (16 cells)
- [x] If a matrix is smaller than 4 x 4, draw matrix in that size
- [x] Keep cells square (rather than rectangular)
- [x] I think Overpass size 10 is a good compromise between clarity and smallness: https://plotly.com/~jackp/18889/
- [x] The matrix and array drawings on this site are a good guide for the style we should be shooting for: http://jsav.io/datastructures/array/
- [x] numbers that are greater than 4 digits or less than 3 digits (eg -999) will need to be displayed with engineering notation to fit in the cell (see https://plotly.com/~jackp/18889/ for mock)

(cc @trbritt @SylvainCorlay @scorinaldi who may have some thoughts/opinions/ideas on this)

**Comment by scorinaldi** [comment]
Cool idea, I have no issue with the look and feel. It would be really nice, if I could select over the numbers, and copy paste them into Excel/ Google Sheets/ whatever. Is there a way to toggle into a different copy / paste-able mode?
