### ISSUE TITLE
Make API key modal wider, style it, and give feedback about success/failure

### ISSUE THREAD

**Issue by jackparmer** [flojoy-io/studio#437]
The input is much shorter than the API key length - it should be longer so that you can see the entire key:

<img width="591" alt="image" src="https://github.com/flojoy-io/studio/assets/1865834/32c4be03-c8a6-45e5-b4b7-7c44849c5cd7">

When I click submit, nothing happens in the UI - it should report success/failure

Finally, the modal needs to be styled according to these mocks

https://www.figma.com/file/jUnFTodDB0dnOKgJMBkY0E/Flojoy_Modals?type=design&node-id=0%3A1&t=x8bMNX0LnKoT1oKZ-1

<img width="1381" alt="image" src="https://github.com/flojoy-io/studio/assets/1865834/964d74a6-04a2-4eda-af0f-54ca5f18996e">

**Comment by smahmed776** [comment]
Resolved via #456
