### ISSUE TITLE
Add unit testing for the settings node delay and maximum runtime

### ISSUE THREAD

**Issue by izi-on** [flojoy-io/studio#444]

**Comment by jackparmer** [comment]
@Jin1L @youngsun4786 
![lest-go](https://github.com/flojoy-io/studio/assets/1865834/11c29a3c-fd9a-443f-86e7-fae564fa49c6)

**Comment by jackparmer** [comment]
can be done with reflect.run

**Comment by Jin1L** [comment]
Made a test in Reflect.run
