### ISSUE TITLE
Update Flojoy logo

### ISSUE THREAD

**Issue by jackparmer** [flojoy-io/studio#450]
Use this avatar logo instead of the ponymaker font text logo in the upper right-hand corner

https://uploads-ssl.webflow.com/63144732ba21d9fe043700ca/6466cb302fb0da75d5ecbf59_fj_avatar-p-500.png

**Comment by jackparmer** [comment]
(In the same PR, also update the favicon please)

**Comment by smahmed776** [comment]
Resolved via #471
