### ISSUE TITLE
shortcut to END node

### ISSUE THREAD

**Issue by jackparmer** [flojoy-io/studio#453]
End nodes always need to be added to terminate a programs execution and clear its queue. 

It's pretty annoying however to have to click down into the logic gate category each time, though. 

Maybe we should add a shortcut for the end node next to the request node button here? 

<img width="355" alt="image" src="https://github.com/flojoy-io/studio/assets/1865834/07e16f18-8a41-4962-b93d-8302d25330d3">

**Comment by smahmed776** [comment]
That's a good idea.
