### ISSUE TITLE
Sidebar/END node bugs

### ISSUE THREAD

**Issue by jackparmer** [flojoy-io/studio#454]
When I search END in the sidebar, nothing comes up:

<img width="399" alt="image" src="https://github.com/flojoy-io/studio/assets/1865834/31950d52-6201-428f-b4e9-e17c15236cf2">

If I search "terminate" however, it does appear:

<img width="393" alt="image" src="https://github.com/flojoy-io/studio/assets/1865834/85bd4a3f-aa5f-49e1-9d40-8c1e9e68d867">

When I click on END, however, this node is not added to the canvas:

<img width="998" alt="image" src="https://github.com/flojoy-io/studio/assets/1865834/6cf26faa-aa30-474b-ae59-0658d838e358">

These are likely 2 separate bugs

**Comment by itsjoeoui** [comment]
@smahmed776 This is similar to the issue I tagged u yesterday, we need to clean it up haha.
