### ISSUE TITLE
Spec out support for editing with keyboard only

### ISSUE THREAD

**Issue by dev-nested** [flojoy-io/studio#485]
[WIP Document]

Our UI consists of multiple panels, for example:
- Node explorer (browse nodes, add node)
- Graph (move nodes)
- Node (remove it, or open its details view)
- Parameters

We can allow users to select panels with keyboard, for example,
p will open parameters panel for the currently selected node.
n will move to next topologically ordered node
a will add a `new node placeholder`, and it'll be placed automatically, it'll automatically open the node explorer in popup
  - the node explorer popup will be a concise text only version of the node explorer (+ icon may be), much like a menu with a search bar on top
  

User can select a node with a search shortcut which will open a search box at the top to select node more decisively.

All our actions would have short cuts already. When user is modifying one panel, the shortcuts would be bound to that panel. Meaning, a short cut that is bound to the currently focused panel would override the same shortcut assigned to actions elsewhere.

**Comment by itsjoeoui** [comment]
moved to linear
