### ISSUE TITLE
Command Bar: Unleash the potential

### ISSUE THREAD

**Issue by itsjoeoui** [flojoy-io/studio#508]
Right now if you press `cmd+k` (or `ctrl+k`), there is a minimal implementation of a command bar. We would like to add more functionalities to it.

Some ideas:
- [ ] Quickly search nodes and add them
- [ ] More actions like open the add node menu, save files, etc. Basically all possible actions you can do with Flojoy Studio
- [ ] Get it styled properly, it looks ugly now

I think this will be bring a HUGE user experience improvement.

https://github.com/flojoy-io/studio/assets/25695219/82268f3e-be42-4186-82bf-8f431286c91c

@jackparmer

**Comment by jackparmer** [comment]
hahaha i think you're just obsessed with Arc

looks like a nice start! could be a nice UX for clearing the canvas, adding nodes, and running new programs

**Comment by itsjoeoui** [comment]
moved to linear
