### ISSUE TITLE
Add data-test flag to the elements in the CTRLS

### ISSUE THREAD

**Issue by Lans1975** [flojoy-io/studio#518]
To automate CTRLS we need to add elements to objects in CTRLS (close btn, dropdown list, elements in dd list)

![Screenshot 2023-06-07 at 7 46 03 AM](https://github.com/flojoy-io/studio/assets/72758315/a5e16539-233e-4ef7-8b55-89fcd2ba1752)

**Comment by jackparmer** [comment]
> To automate CTRLS we need to add elements to objects in CTRLS (close btn, dropdown list, elements in dd list)

@Lans1975 can you be more specific please?

Do you mean adding `data-` identifiers to these 4 elements? 
Any other elements beyond these 4? 

@smahmed776 pls help @Lans1975 once he clarifies to unblock the cypress tests he's writing

**Comment by jackparmer** [comment]
WIP PR by @Jin1L : https://github.com/flojoy-io/studio/pull/623
