### ISSUE TITLE
make plotly colors on-brand in debug panel

### ISSUE THREAD

**Issue by jackparmer** [flojoy-io/studio#522]
these plots are still using plotly default colors:

<img width="1590" alt="image" src="https://github.com/flojoy-io/studio/assets/1865834/72bb8b7e-a790-420e-9992-d7aac7ae9497">

use flojoy.io/brand for acceptable colorway

could create a plotly template in order to reuse colorway from the script panel:

<img width="396" alt="image" src="https://github.com/flojoy-io/studio/assets/1865834/ca00fb81-124e-432b-98c4-fa5a31c9f365">

**Comment by smahmed776** [comment]
Resolve via #543
