### ISSUE TITLE
Investigate codecov accuracy

### ISSUE THREAD

**Issue by jackparmer** [flojoy-io/studio#525]
codecov says we have 70% test coverage, which seems crazy since we only have a few cypress tests? 

can you please check for accuracy and configure codecov as needed @Lans1975 ? 

<img width="342" alt="image" src="https://github.com/flojoy-io/studio/assets/1865834/9796657f-5078-4c2e-a3b4-7f703e268f73">

**Comment by jackparmer** [comment]
(@Lans1975 you should have codecov access automatically by belonging to flojoy's github org - just sign up for codecov and the flojoy studio repo should appear)

**Comment by itsjoeoui** [comment]
This is likely because something is wrong with the Python part, I haven't had a chance to take a deeper look, but the Python report does seem a little sketchy

**Comment by jackparmer** [comment]
@Jin1L @youngsun4786 please write up what you've learned so far here

**Comment by youngsun4786** [comment]
The CodeCov test coverages currently displayed on github are solely based on python tests and jest tests that comprise the TS components.

We figured out how to process test coverages for cypress tests. Once we incorporate these results into github action, they will be reflected.
<img width="1440" alt="Screenshot 2023-06-25 at 8 19 56 PM" src="https://github.com/flojoy-io/studio/assets/83793112/51297bb5-88c1-4312-b31e-859534bbd040">

By switching from jest tests to reflect.run and cypress tests, we aim to increase the test coverage accuracy substantially.

**Comment by youngsun4786** [comment]
> @Jin1L @youngsun4786 please write up what you've learned so far here

 @jackparmer  The CodeCov test coverages currently displayed on github are solely based on python tests and jest tests that comprise the TS components.

We figured out how to process test coverages for cypress tests. Once we incorporate these results into github action, they will be reflected.
<img width="1440" alt="Screenshot 2023-06-25 at 8 19 56 PM" src="https://github.com/flojoy-io/studio/assets/83793112/51297bb5-88c1-4312-b31e-859534bbd040">

By switching from jest tests to reflect.run and cypress tests, we aim to increase the test coverage accuracy substantially.
