### ISSUE TITLE
Improve how multiple inputs are passed to nodes

### ISSUE THREAD

**Issue by dev-nested** [flojoy-io/studio#529]
There is a major issue with nodes with multiple inputs, it seems that the order of the inputs is not guaranteed, which causes problems when the order matters.

The node function signature should be like this

```
def SINE(inputs:dict[str, DataContainer], params:dict)-> Union(DataContainer, dict[str, DataContainer]):
```

Please also update node_styleguide.md for contributors (in the nodes repo)

Support for multiple outputs is covered in this issue https://github.com/flojoy-io/studio/issues/524

**Comment by dev-nested** [comment]
Had a discussion with @JeffDotPng and @itsjoeoui for a better design on how multiple inputs are supported. Here's the new approach we decided to implement.

- The node functions will define all its inputs and params as regular python function parameters with proper type hint.
- All the function parameters that are of DataContainer type are inputs
- All the function parameters that are not DataContainer type are params
- For example, a node with two inputs a and b, and two parameters p and q, will be written as

```
def ADD(a: DataContainer, b: DataContainer, p: int, q: str):
  ...
  ...function body
  ...
```

The `@flojoy` decorator has to properly propagate the arguments to all the function parameters by reading the signature of the target function. It has to utilize the type hints to distinguish inputs from node params.

**Comment by itsjoeoui** [comment]
Thanks Asif for documenting all these, can't wait for us to finish this one. 🚀
