### ISSUE TITLE
[Bug] Force open the browser on startup is broken

### ISSUE THREAD

**Issue by Ben-Epstein** [flojoy-io/studio#559]
When i run `sh flowjoy ...` My browser should open automatically to the host:port I specified, just like `jupyter` or `streamlit` or `solara` etc.

UPDATE: It seems we do open the browser automatically, but it opens _too early_, before the system is ready. So you're taken to a dead page that doesn't refresh once the system is up.

<img width="1086" alt="image" src="https://github.com/flojoy-io/studio/assets/22605641/e19a1bfa-aa11-42e0-ba7a-0be115d066f5">

**Comment by itsjoeoui** [comment]
Closing this since after #588 the electron app will open instead of the browser
