### ISSUE TITLE
Update frontend to work with auto generated manifests

### ISSUE THREAD

**Issue by dev-nested** [flojoy-io/studio#572]
Currently for every new node frontend code is required to be changed (for categorization in node explorer). This issue should make the process fully automated where frontend automatically updates based on the manifests.

Note:
See this related issue: #571 which removes the need for node devs to manually maintain the manifests. The current structure of manifest most likely won't need to be changed. In that case this task can be completed independently.

**Comment by itsjoeoui** [comment]
done
